# base settings
background           = 'black.fg+1'
foreground           = 'black.bg+2'

selection_background = 'black.m+4'
selection_foreground = 'black.bg+3'

cursor               = 'black.bg+2'

# black
color0               = 'black.bg+1'
color8               = 'black.bg+1'

# red
color1               = 'red.m+0'
color9               = 'red.m+0'

# green
color2               = 'green.m+0'
color10              = 'green.m+0'

# yellow
color3               = 'yellow.m+0'
color11              = 'yellow.m+0'

# blue
color4               = 'blue.m+0'
color12              = 'blue.m+0'

# purple (red)
color5               = 'red.m+0'
color13              = 'red.m+0'

# cyan (blue)
color6               = 'blue.m+0'
color14              = 'blue.m+0'

## white
color7               = 'black.fg+2'
color15              = 'black.fg+2'
